# <span style="color:RoyalBlue; ">2.3 Introduction to Python Programming / บทนำสู่การเขียนโปรแกรมภาษา Python</span>

###### <span style="color: gray ">Code 2.1 Trial Program / โค้ด 2.1 โปรแกรมทดลอง</span>

In [1]:
4/2

2.0

###### <span style="color: gray ">code2.2　Basic arithmetic operations</span>

In [1]:
print(3/2)   # Division / การหาร
print(3//2)  # Floor division / การหารปัดเศษลง
print(11%3)  # Remainder / เศษที่เหลือ
print(2**8)  # Exponentiation / การยกกำลัง

1.5
1
2
256


## <span style="color: DeepPink; ">2.3.1 Keyboard Shortcuts and Markdown / คีย์ลัดและ Markdown</span>

###### <span style="color: gray ">Code 2.3 Markdown / โค้ด 2.3 มาร์กดาวน์</span>

### Jupyter Notebook Shortcut Summary / สรุปคีย์ลัดของ Jupyter Notebook  
#### Jupyter Notebook Shortcut Summary / สรุปคีย์ลัดของ Jupyter Notebook  
- <kbd>H</kbd>: Show help / แสดงคำแนะนำ  
- <kbd>M</kbd>: Change to Markdown cell / เปลี่ยนเป็นเซลล์ Markdown  
- <kbd>Ctrl</kbd>+<kbd>Enter</kbd>: Run the current cell / รันเซลล์ปัจจุบัน  
- <kbd>Shift</kbd>+<kbd>Enter</kbd>: Run the current cell and move down / รันเซลล์แล้วเลื่อนไปยังเซลล์ถัดไป  
- <kbd>Ctrl</kbd>+<kbd>/</kbd>: Comment out / คอมเมนต์โค้ด  
- <kbd>Y</kbd>: Change to Code cell / เปลี่ยนเป็นเซลล์โค้ด  
- <kbd>A</kbd>: Insert an empty cell above / แทรกเซลล์ว่างด้านบน  
- <kbd>B</kbd>: Insert an empty cell below / แทรกเซลล์ว่างด้านล่าง  
- <kbd>D</kbd><kbd>D</kbd>: Delete cell / ลบเซลล์  

## <span style="color: DeepPink; ">2.3.2 Handling Variables / การจัดการตัวแปร</span>

###### <span style="color: gray ">Code 2.4 Handling Variables / โค้ด 2.4 การจัดการตัวแปร</span>

In [2]:
a = 10
b = 5
S = a**2 * 3.14
print('The area of the circle is', S)  # / พื้นที่ของวงกลมคือ

The area of the circle is 314.0


## <span style="color: DeepPink; ">2.3.3 Lists / ลิสต์</span>

###### <span style="color: gray ">Code 2.5 Lists / โค้ด 2.5 ลิสต์</span>

In [3]:
number = [1, 2, 3, 4, 5]  # List / ลิสต์
print(number)

[1, 2, 3, 4, 5]


###### <span style="color: gray ">Code 2.6 Data Types / โค้ด 2.6 ชนิดของข้อมูล</span>

In [4]:
# Integer = int type / จำนวนเต็ม = ชนิด int  
# Floating point number = float type / ทศนิยม = ชนิด float  
# String = str type / สตริง = ชนิด str  
# Boolean (True[1], False[0]) = bool type / ค่าความจริง (True[1], False[0]) = ชนิด bool

A = "This is a string"
print(A)
print("The data type of the variable is", type(A))  # / ชนิดของตัวแปรคือ

This is a string
The data type of the variable is <class 'str'>


###### <span style="color: gray ">Code 2.7 List Operations / โค้ด 2.7 การจัดการลิสต์</span>

In [5]:
data = ['Height', 175, 'Weight', 60]
print('The contents of the list are', data)  # ① List contents / เนื้อหาภายในลิสต์
print('The length of the list is', len(data))  # ② List length / ความยาวของลิสต์
print('The first element of the list is', data[0])  # ③ First element of list (index starts from 0) / สมาชิกตัวแรกของลิสต์ (เริ่มนับจาก 0)
print('The third element of the list is', data[2])  # ④ Third element / สมาชิกตัวที่สาม
data[3] = 45  # ⑤
print('The updated contents of the list are', data)  # ⑥ Updated list contents / เนื้อหาลิสต์ที่อัปเดตแล้ว

The contents of the list are ['Height', 175, 'Weight', 60]
The length of the list is 4
The first element of the list is Height
The third element of the list is Weight
The updated contents of the list are ['Height', 175, 'Weight', 45]


## <span style="color: DeepPink; ">2.3.4 Tuples / ทูเพิล</span>

###### <span style="color: gray ">Code 2.8 Tuples / โค้ด 2.8 ทูเพิล</span>

In [6]:
# Tuple definition / การกำหนดทูเพิล
data = ("Height", 175, "Weight", 60)
print("The contents of the tuple are", data)  # Display tuple contents / แสดงเนื้อหาของทูเพิล
print("The length of the tuple is", len(data))  # Display length / แสดงความยาว
print("The first element of the tuple is", data[0])  # Access by index / เข้าถึงสมาชิกด้วยดัชนี
print("The third element of the tuple is", data[2])  # Access by index / เข้าถึงสมาชิกด้วยดัชนี
data[3] = 45  # Tuples are immutable, so this will raise an error / ทูเพิลเปลี่ยนแปลงค่าไม่ได้ จะเกิดข้อผิดพลาด

The contents of the tuple are ('Height', 175, 'Weight', 60)
The length of the tuple is 4
The first element of the tuple is Height
The third element of the tuple is Weight


TypeError: 'tuple' object does not support item assignment

## <span style="color: DeepPink; ">2.3.5 Boolean Type (bool) / ชนิดข้อมูลบูลีน (bool)</span>

###### <span style="color: gray ">Code 2.9 Boolean Type and Conditional Expressions / โค้ด 2.9 ชนิดบูลีนและนิพจน์เงื่อนไข</span>

In [7]:
# Boolean type (True or False) / ชนิดบูลีน (จริง หรือ เท็จ)
bool_integer = 100
bool_50 = bool_integer >= 50
bool_200 = bool_integer >= 200
print('The value of bool_integer is', bool_integer)  # / ค่าของ bool_integer คือ
print('Is bool_integer greater than or equal to 50? →', bool_50)  # / bool_integer มากกว่าหรือเท่ากับ 50 หรือไม่?
print('Is bool_integer greater than or equal to 200? →', bool_200)  # / bool_integer มากกว่าหรือเท่ากับ 200 หรือไม่?

The value of bool_integer is 100
Is bool_integer greater than or equal to 50? → True
Is bool_integer greater than or equal to 200? → False


###### <span style="color: gray ">Code 2.10 Boolean Comparison Operators / โค้ด 2.10 การเปรียบเทียบบูลีน</span>

In [8]:
a = 100
print(a == 100)       # Equal to / เท่ากับ
print(a != 100)       # Not equal to / ไม่เท่ากับ
print(a > 80)         # Greater than / มากกว่า
print(a < 80)         # Less than / น้อยกว่า
print(a >= 100)       # Greater than or equal to / มากกว่าหรือเท่ากับ
print(a <= 100)       # Less than or equal to / น้อยกว่าหรือเท่ากับ

True
False
True
False
True
True


## <span style="color: DeepPink; ">2.3.6 if Statement / คำสั่ง if</span>

###### <span style="color: gray ">Code 2.11 if Statement / โค้ด 2.11 คำสั่ง if</span>


In [9]:
Ymoney = 1000
# Ymoney = 450
# Ymoney = 100

if Ymoney >= 200:
    print('You can buy something at the festival')  # / คุณสามารถซื้ออะไรบางอย่างในงานเทศกาลได้
if Ymoney >= 500:
    print('You can buy fried noodles')  # / คุณสามารถซื้อยากิโซบะได้
elif 200 <= Ymoney < 500:
    print('You can buy a candy apple')  # / คุณสามารถซื้อแอปเปิ้ลเคลือบน้ำตาลได้
else:
    print('You cannot buy anything')  # / คุณไม่สามารถซื้ออะไรได้เลย

You can buy something at the festival
You can buy fried noodles


###### <span style="color: gray ">Code 2.12 Indentation / โค้ด 2.12 การเยื้องบรรทัด</span>

if (condition):<BR>
<font color="Red">Indent →</font> statement to execute<BR>  # / เยื้องบรรทัด → คำสั่งที่ต้องการให้ทำงาน
elif (condition):<BR>
<font color="Red">Indent →</font> statement to execute<BR>  # / เยื้องบรรทัด → คำสั่งที่ต้องการให้ทำงาน
else:<BR>
<font color="Red">Indent →</font> statement to execute<BR>  # / เยื้องบรรทัด → คำสั่งที่ต้องการให้ทำงาน


## <span style="color: DeepPink; ">2.3.7 for Loop / คำสั่ง for</span>

###### <span style="color: gray ">Code 2.13 Structure of for Loop / โค้ด 2.13 โครงสร้างของคำสั่ง for</span>

for variable in object<BR>
<font color="Red">Indent →</font> statement to execute<BR>  # / เยื้องบรรทัด → คำสั่งที่ต้องการให้ทำงาน

###### <span style="color: gray ">Code 2.14 Example of for Loop / โค้ด 2.14 ตัวอย่างคำสั่ง for</span>

In [11]:
for i in [0,1,2]:
    print(i)

0
1
2


###### <span style="color: gray ">Code 2.15 range Function / โค้ด 2.15 ฟังก์ชัน range</span>

In [12]:
A = range(5)
print(A)
for i in range(5):
    print(i)

range(0, 5)
0
1
2
3
4


###### <span style="color: gray ">Code 2.16 for Loop and Variables / โค้ด 2.16 คำสั่ง for กับตัวแปร</span>

In [10]:
words = ["python", "with", "spectrum analysis"]
for w in words:
    print(w)  # Print each word in the list / แสดงคำแต่ละคำในลิสต์

python
with
spectrum analysis


## <span style="color: DeepPink; ">2.3.8 Function Definitions / การกำหนดฟังก์ชัน</span>


###### <span style="color: gray ">Code 2.17 Structure of Function Definition Using def Keyword / โค้ด 2.17 โครงสร้างของการกำหนดฟังก์ชันด้วยคีย์เวิร์ด def</span>

def function_name(arguments):<BR>
   <font color="Red">Indent →</font> statement to execute<BR>  # / เยื้องบรรทัด → คำสั่งที่ต้องการให้ทำงาน
   <font color="Red">Indent →</font> return value<BR>  # / เยื้องบรรทัด → ส่งค่ากลับ

###### <span style="color: gray ">Code 2.18 Function Without Arguments or Return Value / โค้ด 2.18 ฟังก์ชันที่ไม่มีอาร์กิวเมนต์และค่าที่ส่งกลับ</span>

In [14]:
def hello():
    print('hello to chemometorics')
    print('for the spectral analysis')
hello()

hello to chemometorics
for the spectral analysis


###### <span style="color: gray ">Code 2.19 Function with Arguments / โค้ด 2.19 ฟังก์ชันที่มีอาร์กิวเมนต์</span>


In [11]:
def show_hello_to(name1, name2):
    print(name1 + ', welcome to chemometrics analysis')  # / ยินดีต้อนรับสู่การวิเคราะห์เคโมเมทริกส์
    print(name2 + ', you can freely analyze the spectra')  # / คุณสามารถวิเคราะห์สเปกตรัมได้อย่างอิสระ

show_hello_to('sakai', 'kato')

sakai, welcome to chemometrics analysis
kato, you can freely analyze the spectra


###### <span style="color: gray ">Code 2.20 Function with Arguments and Return Value / โค้ด 2.20 ฟังก์ชันที่มีอาร์กิวเมนต์และค่าที่ส่งกลับ</span>


In [16]:
def simple_tashizan(a,b,c):
    p1=a+b
    p2=a+c
    p3=b+c
    return p1,p2,p3

d1,d2,d3=simple_tashizan(10,20,30)
print(d1,d2,d3)

30 40 50


# <span style="color:RoyalBlue; ">2.4 Libraries / ไลบรารี</span>

## <span style="color: DeepPink; ">2.4.2 Installing and Importing Libraries / การติดตั้งและนำเข้าไลบรารี</span>

###### <span style="color: gray ">Code 2.21 How to Import a Library (Method 1) / โค้ด 2.21 วิธีการนำเข้าไลบรารี (แบบที่ 1)</span>

In [17]:
import numpy

###### <span style="color: gray ">Code 2.22 How to Import a Library (Method 2) / โค้ด 2.22 วิธีการนำเข้าไลบรารี (แบบที่ 2)</span>

In [18]:
from numpy import array

###### <span style="color: gray ">Code 2.23 How to Import a Library (Method 3) / โค้ด 2.23 วิธีการนำเข้าไลบรารี (แบบที่ 3)</span>

In [19]:
import numpy as np
a = np.array([1, 2, 3])

###### <span style="color: gray ">Code 2.24 Common Usage of the as Keyword / โค้ด 2.24 การใช้คีย์เวิร์ด as ตามธรรมเนียม</span>

In [20]:
import pandas as pd
import matplotlib.pyplot as plt

## <span style="color: DeepPink; ">2.4.3 How to Use Libraries / วิธีการใช้งานไลบรารี</span>

###### <span style="color: gray ">Code 2.24 Methods / โค้ด 2.24 เมทอด</span>

In [12]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6])  # ① Create a 1D array / สร้างอาเรย์ 1 มิติ
print(array)
reshaped_array = array.reshape((2, 3))  # ② Change array shape using reshape() method / เปลี่ยนรูปร่างของอาเรย์ด้วยเมทอด reshape()
print(reshaped_array)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


###### <span style="color: gray ">Code 2.25 Attributes / โค้ด 2.25 แอททริบิวต์</span>

In [13]:
import numpy as np
array = np.array([1, 2, 3])
print(array.shape)  # (3,) - 1D array with 3 elements / อาเรย์ 1 มิติที่มี 3 สมาชิก
print(array.dtype)  # int64 - Data type of each element is 64-bit integer / ชนิดข้อมูลของสมาชิกแต่ละตัวคือจำนวนเต็ม 64 บิต

(3,)
int32
